miwwa/main/routes.py
import os 
import secrets
from PIL import Image
from miwwa import  db, bcrypt
from flask import render_template, url_for, flash, redirect, request, session, g , Blueprint, current_app
from flask_login import login_user, current_user, logout_user, login_required
from miwwa.main.forms import * 
from sqlalchemy import desc
from sqlalchemy.sql import func
from miwwa.models import *
import uuid
from datetime import datetime, timedelta
from miwwa.main.utils import *
import requests 








main = Blueprint('main', __name__)




today = datetime.utcnow().strftime("%Y-%m-%d")


# def get_country(ip_address):
#     try:
#         response = requests.get(f"http://ip-api.com/json/{ip_address}")
#         js = response.json()
#         country = js['countryCode']
#         return country
#     except Exception as e:
#         return "Unknown"


@main.route('/',methods=['GET', 'POST'])
def home():
    if current_user.is_authenticated:
        return redirect(url_for('main.profile'))
    if request.environ.get('HTTP_X_FORWARDED_FOR') is None:
        current_app.logger.info(request.environ['REMOTE_ADDR'])
    else:
        current_app.logger.info(request.environ['HTTP_X_FORWARDED_FOR'])
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(phone=form.phone.data).first()
        if user and bcrypt.check_password_hash(user.password,form.password.data):
            login_user(user)
            if user.verified == False:
                return redirect(url_for('main.complete_reg'))
            return redirect(url_for('main.profile'))
        else:
            print('Phone or Password Incorrect')
            flash('Phone or Password Incorrect', 'warning')
    return render_template('main/index.html', title='Homepage', form=form)
    
 

 
@main.route('/profile') 
@login_required
def profile():
    user = User.query.filter_by(id=current_user.id).first()
    officer = Officer.query.filter_by(user_id=user.id).first()
    upload = Upload.query.filter_by(user_id=user.id).first()
    if user.verified == False:
        return redirect(url_for('main.complete_reg'))
    return render_template('main/profile.html', user=user,officer=officer,upload=upload)

@main.route('/register', methods=['GET','POST'])
def reg_personal():
    form = RegisterPersonalForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(first_name=form.first_name.data,last_name=form.last_name.data,email=form.email.data,phone=form.phone.data,password=hashed_password,address=form.address.data,state_of_resident=form.state_of_residence.data,dob=form.dob.data,occupation=form.occupation.data,interest=form.area_of_interest.data,number_of_children=form.no_of_children.data)
        db.session.add(user)
        db.session.commit()
        session['user_id'] = user.id
        requests.post(f"http://www.smsmobile24.com/index.php?option=com_spc&comm=spc_api&username=MZYF&password=MZYFS&sender=MIWA Admin&recipient={user.phone}&message= Thank You for creating a Miwa Account, Please complete your registration and get verified !  &")
        return redirect(url_for('main.reg_officer'))
    else:
        print(form.errors)
    return render_template('main/registerone.html', form=form)

@main.route('/register/officer',methods=['GET','POST'] )
def reg_officer():
    form = RegisterOfficerInfo()
    if form.validate_on_submit():
        user_id = session.get('user_id')
        user = User.query.filter_by(id=user_id).first() 
        print(user.first_name)
        inc_officer = Officer.query.filter_by(user_id=user_id).first()
        if inc_officer:
            inc_officer.first_name = form.first_name.data
            inc_officer.last_name = form.last_name.data
            inc_officer.state_of_origin = form.state_of_origin.data
            inc_officer.service_no = form.service_number.data
            inc_officer.rank = form.rank.data
            inc_officer.dod = form.dod.data
            db.session.commit()
        new_officer = Officer(first_name=form.first_name.data,last_name=form.last_name.data,state_of_origin=form.state_of_origin.data,service_no=form.service_number.data,rank=form.rank.data,dod=form.dod.data,user_id=user.id)
        db.session.add(new_officer)
        db.session.commit()
        return redirect(url_for('main.reg_upload'))
    else:
        print(form.errors)
    return render_template('main/registertwo.html', form=form)

@main.route('/register/uploads',methods=['GET','POST'] )
def reg_upload():
    form = RegisterUploads()
    if form.validate_on_submit():
        user_id = session.get('user_id')
        user = User.query.filter_by(id=user_id).first()
        print(user.first_name)
        if form.death_cert.data:
            death_cert = save_document(form.death_cert.data)
        if form.other.data:
            thumbnail = save_profile_thumbnail(form.other.data)
        inc_user_upload = Upload.query.filter_by(user_id=user_id).first()
        if inc_user_upload:
            inc_user_upload.death_cert = death_cert
            db.session.commit()
        new_upload = Upload(death_cert=death_cert,user_id=user.id)
        db.session.add(new_upload)
        user.thumbnail = thumbnail 
        user.verified = True
        user.verified_at = today
        db.session.commit()
        requests.post(f"http://www.smsmobile24.com/index.php?option=com_spc&comm=spc_api&username=MZYF&password=MZYFS&sender=MIWA Admin&recipient={user.phone}&message= Congratulations! Your Miwa account has been verified.  &")
        return redirect(url_for('main.acct_login'))
    return render_template('main/registerthree.html', form=form)


@main.route('/registration_successful')
def acct_login():
    return render_template('main/complete_reg.html', title='Account Created')


@main.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@main.route('/reset_password', methods=['GET','POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.profile')) 
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instruction to reset your password', 'info')
        return redirect(url_for('main.home'))
    return render_template('main/forgot-password.html', title='Reset Password',form=form)

@main.route('/reset_password/<token>', methods=['GET','POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.profile'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('main.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You can now login', 'success')
        return redirect(url_for('main.home'))
    return render_template('main/reset-password.html', title='Reset Password', form=form)



@main.route('/welcome_back',methods=['GET','POST'])
def update_one():
    if current_user.is_authenticated:
        return redirect(url_for('main.profile'))
    form = UpdateOneForm()
    if form.validate_on_submit():
        user = User.query.filter_by(phone=form.phone.data).first()
        if user.first_name is None:
            session['user_id'] = user.id
            return redirect(url_for('main.update_personal'))
        elif not user:
            flash('Please go and register, This page is mainly for account update !')
        else:
            flash('You are not allowed to edit here. Please request for password change', 'warning')
    return render_template('main/update_welcome.html',form=form,title='Welcome Back. Please Update your account ! ')

@main.route('/update_personal',methods=['GET','POST'])
def update_personal():
    form = UpdatePersonalForm()
    user_id = session.get('user_id')
    user = User.query.filter_by(id=user_id).first()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.first_name = form.first_name.data
        user.last_name = form.last_name.data
        user.email = form.email.data
        user.password = hashed_password
        user.address = form.address.data
        user.state_of_resident = form.state_of_residence.data
        user.dob = form.dob.data
        user.occupation = form.occupation.data
        user.interest = form.area_of_interest.data
        user.number_of_children = form.no_of_children.data
        db.session.commit()
        return redirect(url_for('main.update_officer'))
    return render_template('main/update_registerone.html',form=form, user=user, title='Update Personal Details')

@main.route('/update_officer_info', methods=['GET','POST'])
def update_officer():
    form = UpdateOfficerForm()
    if form.validate_on_submit():
        user_id = session.get('user_id')
        user = User.query.filter_by(id=user_id).first()
        print(user.first_name)
        new_officer = Officer(first_name=form.first_name.data,last_name=form.last_name.data,state_of_origin=form.state_of_origin.data,service_no=form.service_number.data,rank=form.rank.data,dod=form.dod.data,user_id=user.id)
        db.session.add(new_officer)
        db.session.commit()
        return redirect(url_for('main.update_uploads'))
    else:
        print(form.errors)
    return render_template('main/update_registertwo.html', form=form, title='Update Officer Details ')

@main.route('/update_uploads',  methods=['GET','POST'])
def update_uploads():
    form = UpdateUploadsForm()
    if form.validate_on_submit():
        user_id = session.get('user_id')

miwwa/templates/main/coming-soon.html
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
       
        {% if title %}
        <title> MIWA - {{ title }}  </title>
        {% else %}
        <title> MIWA </title>
        {% endif %}
        <link rel="icon" href= "img/zealhost_logo.png" sizes="20x20"> <!-- insert zealhost icon here -->
        <style>

            body{
                background-image: url(   {{ url_for('static', filename='img/coming-soon-bg.jpg') }} );
                background-repeat: no-repeat;
                background-size: cover;
            }
            
        .test{
           height: 100%;
           background-repeat: no-repeat;
           background-position: center;
    
        }

        .move-zeal-logo{
            position: absolute;
            top: 40%;
            left: 50%;
            transform: translate(-50%,-50%);
        }


        .move-zeal-text{
          position: absolute;
            top: 55%;
            left:50%;
            transform: translate(-50%,-50%);
        }
                </style>
        <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>

    </head>
    <body>
      
        <div class="test">
            <div class="move-zeal-logo">
             <img src=" {{ url_for('static', filename='img/miwa_resized.svg') }}">
            </div>
            <div class="move-zeal-text">
             <p>Our site is currently under construction. Thank you for your patience.</p>
            </div>
        </div>

    </body>
</html>

miwwa/templates/main/complete_reg.html
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv= "X-UA-compatible"content="IE-edge">
        {% if title %}
        <title> MIWA - {{ title }}  </title>
        {% else %}
        <title> MIWA </title>
        {% endif %}
        <link  rel = "stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
        <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
    </head>
    <body>
          <section class="home_bg">  
            <div class="container">
               
                
            <nav class="navbar navbar-expand-lg navbar-dark">
              <a class="navbar-brand" href="#">
                    <div class="text-left mb-4">
            <img src="{{ url_for('static', filename='img/miwa_resized.svg') }}" height="">
            </div>
                </a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item active">
                    <a class="nav-link " href="#">Testimonials <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.faqs') }}">About Us</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.contact_us') }}">Contact US</a>
                  </li>

                </ul>
              </div>
            </nav>
            
            <div class = "row">
                <div class="col-md-6 white-txt-color">
                    <div class= "center-text">
                    <h3 style ="font-size:55px;">Registration Sucessful</h3>
                    
                    </div>
                    <div class="for-bottom container">
                        <div class='row'>
                           <div class='col-md-4'> 
                               <small>Legion House</small><br>
                               <small>Area 3 Garki Abuja</small>
                            </div> 
                            <div class='col-md-4'> 
                                <small>08034411192</small>
                                <small>08187656654</small>
                                
                            </div> 
                            <div class='col-md-4'> 
<!--                                 <i class="fas fa-phone fa-3x mb-3 text-muted"></i>-->
                                
                                <small><i class="fa fa-facebook"></i> </small>
                                <small><i class="fa fa-twitter"></i> </small>
                                <small><i class="fa fa-instagram"></i> </small>
                            </div>
                            
                        </div>
                        
                    </div>
                </div>
                <div class="counter_form">
				<div class="row fill_height">
					<div class="col fill_height">
						<form class="counter_form_content d-flex flex-column align-items-center justify-content-center" action="#">
							<div class="counter_form_title">
                            <img src="{{ url_for('static', filename='img/miwa_resized.svg') }}" height="">
                            </div>
                          <a class="btn counter_form_button" href=" {{ url_for('main.home') }}"> Login </a>
							
                            
						</form>
					</div>
				</div> 
			</div>
                
            </div>
            </div>
        </section>
       
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script> 
    </body>
</html>

miwwa/templates/main/dashboard.html
<html>
        <head>
        <meta charset="utf-8">
        <meta http-equiv= "X-UA-compatible"content="IE-edge">
        <title>MIWA Dashboard </title>
        <link  rel = "stylesheet" href="css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="css/style.css">
        <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
        <link href="fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css"> <!--check to see what is wrong with this link-->
        
        <!-- Add icon library -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    

    <body>
        
    </body>
</html>

miwwa/templates/main/index.html
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv= "X-UA-compatible"content="IE-edge">
        {% if title %}
        <title> MIWA - {{ title }}  </title>
        {% else %}
        <title> MIWA </title>
        {% endif %}
        <link  rel = "stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
        <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
        <link href="{{ url_for('static', filename='fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css"> <!--check to see what is wrong with this link-->
        
        <!-- Add icon library -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    <body class="for-index">
      
    <section class="home_bg"> 
        <div class="container">       
              <header class="head-main">
                  <div class="navbar navbar-dark bglight box-shadow">
                    <div class="container d-flex justify-content-between">
                      <a href="#" class="navbar-brand d-flex align-items-center">
                        <img src="{{ url_for('static', filename='img/miwa_resized.svg') }}" height="">
                      </a>
                      <a class="nav-button ml-auto mr-4"><span id="nav-icon3">
                          <span></span><span></span><span></span><span></span></span></a>
                    </div>
                  </div> <!--navbar end-->

                  <div class="fixed-top main-menu">
                    <div class="flex-center p-5">
                      <ul class="nav flex-column">
                        <li class="nav-item delay-1"><a class="nav-link" href="{{ url_for('main.home') }}">HOME</a></li>
                
                        <li class="nav-item delay-3"><a class="nav-link" href="{{ url_for('main.aboutus') }}">ABOUT US</a></li>
                        <li class="nav-item delay-4"><a class="nav-link" href="{{ url_for('main.events') }}">EVENTS</a></li>
                        <li class="nav-item delay-5"><a class="nav-link" href="{{ url_for('main.contact_us') }}">CONTACT US</a></li>
                        <li class="nav-item delay-6"><a class="nav-link" id="smedia-nav" href="#">Facebook</a></li>
                        <li class="nav-item delay-6"><a class="nav-link" id="smedia-nav" href="https://twitter.com/MiwaNigeria">Twitter</a></li>
                        <li class="nav-item delay-6"><a class="nav-link" id="smedia-nav" href="https://www.instagram.com/miwanigeria/">Instagram</a></li>
       
                      </ul>
                    </div>
                  </div> <!--main-menu end-->
                </header>

            <div class = "row">
                <div class="col-md-6 white-txt-color">
                    <div class= "center-text">
                    <h3 style ="font-size:55px;">Welcome To Miwa</h3>
                    <p class="text-center">"Life Without Our Husband</p>
                    </div>
                    
                    <div class="for-bottom container">
                        <div class='row'>
                           <div class='col-md-4'> 
                               <small>Legion House</small><br>
                               <small>Area 3 Garki Abuja</small>
                            </div> 
                            <div class='col-md-4'> 
                                <small>08034411192</small>
                                <small>08187656654</small>
                                
                            </div> 
                            <div class='col-md-4'>                                
                                <small><a class="smedia" href="#"><i class="fa fa-facebook"></i> </a></small>
                                <small><a class="smedia" href="https://twitter.com/MiwaNigeria"><i class="fa fa-twitter"></i></a></small>
                                <small><a class="smedia" href="https://www.instagram.com/miwanigeria/"><i class="fa fa-instagram"></i> </a></small>
                            </div>
                            
                        </div>
                        
                    </div>
                </div>
                <div class="counter_form">
                  <div class="row fill_height">

                    <div>
                        {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for category, message in messages %}
                                <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                                    <span>{{ message }}</span>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                    </div>
        
                  <div class="col fill_height">
                      <form class="counter_form_content d-flex flex-column align-items-center justify-content-center" action="" method="POST">
                          {{ form.hidden_tag() }}
                        <div class="counter_form_title">
                                      <img src=" {{ url_for('static', filename='img/miwa_resized.svg') }}" height=""> 
                                      </div>
                                      
                        {% if form.phone.errors %}
                        {{ form.phone(type="tel",class="counter_input", placeholder="Phone Number", required="required")}}
                        <div class="invalid-feedback d-block">
                          {% for error in form.phone.errors %}
                          <span> {{ error }} </span>
                          {% endfor %}
                        </div>
                        {% else %}
                        {{ form.phone(type="tel",class="counter_input",  placeholder="Phone Number")}}
                        {% endif %}
                       
                        {% if form.password.errors %}
                        {{ form.password(type="password",class="counter_input",  placeholder="Password",required="required")}}
                        <div class="invalid-feedback d-block">
                          {% for error in form.password.errors %}
                          <span> {{ error }} </span>
                          {% endfor %}
                        </div> 
                        {% else %}
                        {{ form.password(type="password",class="counter_input",placeholder="Password",required="required")}}
                        {% endif %}
                        <small> Need an account? <a href=" {{ url_for('main.reg_personal') }}"> Register Now </a></small>
                      
                        {{ form.submit(type="submit",class="counter_form_button")}}
                        <small> <a href="{{ url_for('main.reset_request') }}"> Forgot Password ? </a> </small>
                                      
                      </form>
                  </div>
                </div>
			</div>
                
            </div>
            </div>
        </section>
        

        
         <section class="for-mobile text-center">
             <header class="head-main">
                  <div class="navbar navbar-dark bglight box-shadow">
                    <div class="container d-flex justify-content-between">
                      <a href="#" class="navbar-brand d-flex align-items-center">

                      </a>
                      <a class="nav-button ml-auto mr-4"><span id="nav-icon3">
                          <span></span><span></span><span></span><span></span></span></a>
                    </div>
                  </div> <!--navbar end-->

                  <div class="fixed-top main-menu">
                    <div class="flex-center p-5">
                      <ul class="nav flex-column">
                        <li class="nav-item delay-1"><a class="nav-link" href="{{ url_for('main.home') }}">HOME</a></li>
                
                        <li class="nav-item delay-3"><a class="nav-link" href="{{ url_for('main.aboutus') }}">ABOUT US</a></li>
                        <li class="nav-item delay-4"><a class="nav-link" href="{{ url_for('main.events') }}">EVENTS</a></li>
                        <li class="nav-item delay-5"><a class="nav-link" href="{{ url_for('main.contact_us') }}">CONTACT US</a></li>
                        <li class="nav-item delay-6"><a class="nav-link" id="smedia-nav" href="#">Facebook</a></li>
                        <li class="nav-item delay-6"><a class="nav-link" id="smedia-nav" href="https://twitter.com/MiwaNigeria">Twitter</a></li>
                        <li class="nav-item delay-6"><a class="nav-link" id="smedia-nav" href="https://www.instagram.com/miwanigeria/">Instagram</a></li>
       
                      </ul>
                    </div>
                  </div> 
                </header>

             <div class="mobile-wrap">

                <div>
                    {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                                <span>{{ message }}</span>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                </div>
               
						<form class="counter_form_content d-flex flex-column align-items-center justify-content-center" action="" method="POST">
                          {{ form.hidden_tag() }}
                        <div class="counter_form_title">
                                      <img src=" {{ url_for('static', filename='img/miwa_resized.svg') }}" height=""> 
                                      </div>
                                      
                        {% if form.phone.errors %}
                        {{ form.phone(type="tel",class="counter_input", placeholder="Phone Number", required="required")}}
                        <div class="invalid-feedback d-block">
                          {% for error in form.phone.errors %}
                          <span> {{ error }} </span>
                          {% endfor %}
                        </div>
                        {% else %}
                        {{ form.phone(type="tel",class="counter_input",  placeholder="Phone Number")}}
                        {% endif %}
                       
                        {% if form.password.errors %}
                        {{ form.password(type="password",class="counter_input",  placeholder="Password",required="required")}}
                        <div class="invalid-feedback d-block">
                          {% for error in form.password.errors %}
                          <span> {{ error }} </span>
                          {% endfor %}
                        </div> 
                        {% else %}
                        {{ form.password(type="password",class="counter_input",placeholder="Password",required="required")}}
                        {% endif %}
                        <small> Need an account? <a href=" {{ url_for('main.reg_personal') }}"> Register Now </a></small>
                      
                        {{ form.submit(type="submit",class="counter_form_button")}}
                        <small> <a href="{{ url_for('main.reset_request') }}"> Forgot Password ? </a> </small>
                                      
                      </form>
                     

			</div>
        </section>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script>
              $(document).ready(function(){
              $('.nav-button').click(function(){
                $('body').toggleClass('nav-open');
              });
            });
        </script>
       <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
       <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script> 
    </body>
</html>